const ActionType = {
  REGISTER_START: "REGISTER_START",
  REGISTER_FAIL: "REGISTER_FAIL",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",

  SET_USER: "SET_USER",

  GOOGLE_SIGNUP_START: "GOOGLE_SIGNUP_START",
  GOOGLE_SIGNUP_SUCCESS: "GOOGLE_SIGNUP_SUCCESS",
  GOOGLE_SIGNUP_FAIL: "GOOGLE_SIGNUP_FAIL",

  LOGIN_START: "LOGIN_START",
  LOGIN_FAIL: "LOGIN_FAIL",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
};

export default ActionType;
