const ContactListAction = {
  GET_CONTACT_LIST: "GET_CONTACT_LIST",
  LOADING_CONTACT_LIST: "LOADING_CONTACT_LIST",
  SUCCESS_ADD_CONTACT_LIST: "SUCCESS_ADD_CONTACT_LIST",
  FAIL_ADD_CONTACT_LIST: "FAIL_ADD_CONTACT_LIST",
};
export default ContactListAction;
