export const MessageAction = {
  SEND_MESSAGE_START: "SEND_MESSAGE_START",
  SEND_MESSAGE_SUCCESS: "SEND_MESSAGE_SUCCESS",
  SEND_MESSAGE_FAIL: "SEND_MESSAGE_FAIL",

  CURRENT_GROUP: "CURRENT_GROUP",
};
