const ProfileAction = {
  IMAGE_UPLOAD_START: "IMAGE_UPLOAD_START",
  IMAGE_UPLOAD_SUCCESS: "IMAGE_UPLOAD_SUCCESS",
  IMAGE_UPLOAD_FAIL: "IMAGE_UPLOAD_FAIL",

  FIELD_UPDATE_START: "FIELD_UPDATE_START",
  FIELD_UPDATE_SUCCESS: "FIELD_UPDATE_SSUCCESS",
  FIELD_UPDATE_FAIL: "FIELD_UPDATE_FAIL",
};
export default ProfileAction;
